version "4.11"

//#include "scripts/player.zs"
#include "scripts/marathonactor.zs"
#include "scripts/fighter.zs"
#include "scripts/trooper.zs"
#include "scripts/enforcer.zs"
#include "scripts/compiler.zs"
#include "scripts/juggernaut.zs"
#include "scripts/bob.zs"
#include "scripts/events.zs"
#include "scripts/hud.zs"